select * from offices;
select table_name from user_tables;
select city, target, sales from offices;
select city, target, sales from offices where region = 'Запад';
select city, target, sales from offices where region = 'Запад' and sales > target order by city;
select avg(target), avg(sales) from offices where region  = 'Запад';
select name, rep_office, hire_date from salesreps;
select name, quota, sales from salesreps where empl_num = 107;
select avg(sales) from salesreps where empl_num = 107;
select name, hire_date from salesreps where sales > 50000;
select name, manager, quota from salesreps;
select city, region, sales from offices;
select city, region, (sales-target) from offices;
select city region, '$ ' ||(sales-target) as stoim from offices;
select mfr_id, product_id, description, (qty_on_hand * price) from products;
select mfr_id, product_id, description, '$ '||(qty_on_hand * price) as stoim from products;
select name, quota, (quota +((sales/100)*3)) from salesreps;
select city, 'Has sales of', sales from offices;
select * from offices; 
select mgr from offices;
select distinct mgr from offices;
select city, sales, target from offices where sales > target;
select sales , name, quota from salesreps where empl_num = 105;
select name, sales from salesreps where manager = 104;
select name from salesreps where hire_date < to_date('01.06.1988', 'DD/MM/YYYY');
select city mgr from offices where mgr <> 108;
select city, mgr from offices where mgr != 108;
select city, sales, target from offices where sales < (0.8 * target);
select order_num, order_date, mfr, product, amount from orders where order_date between to_date('01.11.1989','DD/MM/YYYY') and to_date ('31.12.1989','DD/MM/YYYY');
select order_num, amount from orders where amount between 20.000 and 29.999;
select order_num, amount from orders where amount between 30.000 and 39.999;
select order_num, amount from orders where amount between 1.000 and 9.999;
select name, sales, quota from salesreps where sales not between (0.8 * quota) and (1.2 * quota);
select name, quota, sales from salesreps where rep_office in (11, 13, 22);
select order_num, order_date, amount from orders where order_date in (to_date('14.06.1990','DD/MM/YYYY'), to_date('08.06.1990','DD/MM/YYYY'), to_date('29.06.1990','DD/MM/YYYY'), to_date('04.06.1990','DD/MM/YYYY'));
select order_num, rep, amount from orders where rep in (107, 109, 101, 103);
select company, credit_limit from customers where company = 'Апельсин';
select company, credit_limit from customers where company like '%н';
select company, credit_limit from customers where company like '%бесы';
select company, credit_limit from customers where company like 'Ап_льсин';
select name from salesreps where rep_office = null;
select name from salesreps where rep_office is null;
select name from salesreps where rep_office is not null;
select name, quota, sales from salesreps where sales < quota or sales < 300.0;
select name, quota, sales from salesreps where sales < quota and sales < 300.0;
select name, quota, sales from salesreps where (sales < quota) and (not sales > 150.000);
select name from salesreps where (rep_office in (22,11,12)) or (manager is null and hire_date >= to_date('01.05.88','DD/MM/YYYY')) or (sales > quota and not sales > 60.0);
select city, region, sales from offices order by region, city;
select city, region, sales from offices order by sales desc;
select city, region, (sales - target) from offices order by 3 desc;
select city, region, (sales - target) from offices order by region asc, 3 desc;
select mfr_id, product_id from products where price > 500.00;
select distinct mfr, product from orders where amount > 4.00;
select mfr_id, product_id from products where price > 500.00 union select distinct mfr, product from orders where amount > 4.00;
select mfr_id, product_id from products where price > 500.00 union all select distinct mfr, product from orders where amount > 4.00;
select mfr_id, product_id from products where price > 500.00 union all select distinct mfr, product from orders where amount > 4.00 order by 1, 2;